# Generated by Django 4.1.7 on 2023-02-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_number', models.CharField(max_length=12)),
                ('to_number', models.CharField(max_length=12)),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
